server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ibeer_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.json

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        default_schema: public
        ddl-auto: validate
        show_sql: true
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
          lob:
            non_contextual_creation: true
          temp:
            use_jdbc_metadata_defaults: false