version: '3.5'

services:
  ibeer-db:
    image: postgres:latest
    networks:
      ibeer-network:
        ipv4_address: 172.17.0.5
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ibeer-db_data:/var/lib/postgresql/data
    container_name: ibeer-db
    environment:
      POSTGRES_DB: ibeer_db
      POSTGRES_PASSWORD: secret

networks:
  ibeer-network:
    ipam:
      driver: default
      config:
        - subnet: 172.17.0.0/16
volumes:
  ibeer-db_data:
    driver: local